name: CI

on:
  push:
    branches: [ master ]
    tags: [ v* ]
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  pull-requests: read
  # Optional: allow write access to checks to allow the action to annotate code in the PR.
  checks: write

jobs:
  test:
    strategy:
      matrix:
        go-version: [stable]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout
        uses: actions/checkout@v4

      - name: Run tests with race detector
        run: go test -count=1 -race ./...

      # - name: Run golangci-lint
      #   uses: golangci/golangci-lint-action@v6
      #   with:
      #     only-new-issues: false
      #     version: latest
